// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqppsNLUMtJfhdX1ugEjxck99dDFxi7Kw',
    appId: '1:748763284882:web:fab1c6224ce61de2052d4b',
    messagingSenderId: '748763284882',
    projectId: 'agri-smart-77b3c',
    authDomain: 'agri-smart-77b3c.firebaseapp.com',
    storageBucket: 'agri-smart-77b3c.firebasestorage.app',
    measurementId: 'G-NKB31XCHJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnCJlpSpRd5KYiiysfS9Lp3GJJxXTcAA',
    appId: '1:748763284882:android:74a5180546b69eac052d4b',
    messagingSenderId: '748763284882',
    projectId: 'agri-smart-77b3c',
    storageBucket: 'agri-smart-77b3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASwX341nf8D33pOcJk6ZzW6bpjRjj90KU',
    appId: '1:748763284882:ios:c3251ec4a2d578fb052d4b',
    messagingSenderId: '748763284882',
    projectId: 'agri-smart-77b3c',
    storageBucket: 'agri-smart-77b3c.firebasestorage.app',
    iosBundleId: 'com.example.agriSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASwX341nf8D33pOcJk6ZzW6bpjRjj90KU',
    appId: '1:748763284882:ios:c3251ec4a2d578fb052d4b',
    messagingSenderId: '748763284882',
    projectId: 'agri-smart-77b3c',
    storageBucket: 'agri-smart-77b3c.firebasestorage.app',
    iosBundleId: 'com.example.agriSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqppsNLUMtJfhdX1ugEjxck99dDFxi7Kw',
    appId: '1:748763284882:web:3b72cf68f80ea9fe052d4b',
    messagingSenderId: '748763284882',
    projectId: 'agri-smart-77b3c',
    authDomain: 'agri-smart-77b3c.firebaseapp.com',
    storageBucket: 'agri-smart-77b3c.firebasestorage.app',
    measurementId: 'G-70SF9TTM6C',
  );

}